name: Deploy to IIS

on:
  push:
    branches: [ "master" ]   # غيّرها لـ "main" لو ده الفرع الافتراضي عندك

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows, X64]   # مهم جداً: لازم تستخدم نفس الـ labels اللي ظهرت في صفحة GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish .NET app
        run: dotnet publish -c Release -o publish

      - name: Deploy to IIS (without touching wwwroot)
        shell: powershell
        run: |
          $source = "$(Get-Location)\publish\*"
          $dest   = "C:\Users\Dhiaa\Desktop\New folder (4)\ware"

          # انسخ كل حاجة ماعدا wwwroot
          robocopy $source $dest /MIR /XD wwwroot

          # Restart IIS
          iisreset
